name: Nivesh
options:
  bundleIdPrefix: com.hvm
  deploymentTarget:
    iOS: "16.0"
targets:
  Nivesh:
    type: application
    platform: iOS
    sources:
      - Nivesh
    settings:
      base:
        INFOPLIST_FILE: Nivesh/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.hvm.nivesh
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
